"""initial_schema

Revision ID: 62e4c0502b57
Revises: 
Create Date: 2025-12-09 10:21:06.856497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e4c0502b57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('other_documents', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_other_documents_original_filename'), 'other_documents', ['original_filename'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_other_documents_original_filename'), table_name='other_documents')
    op.drop_column('other_documents', 'original_filename')
    # ### end Alembic commands ###
