"""initial_schema_sqlite

Revision ID: 5f7dcef898c7
Revises: 
Create Date: 2025-12-10 11:13:32.656878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f7dcef898c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('total_without_vat', sa.Float(), nullable=True),
    sa.Column('total_with_vat', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('raw_vlm_json', sa.JSON(), nullable=True),
    sa.Column('raw_vlm_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_original_filename'), 'invoices', ['original_filename'], unique=False)
    op.create_index(op.f('ix_invoices_provider'), 'invoices', ['provider'], unique=False)
    op.create_table('other_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_other_documents_id'), 'other_documents', ['id'], unique=False)
    op.create_index(op.f('ix_other_documents_original_filename'), 'other_documents', ['original_filename'], unique=False)
    op.create_index(op.f('ix_other_documents_provider'), 'other_documents', ['provider'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_ht', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_id'), 'invoice_lines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_lines_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_other_documents_provider'), table_name='other_documents')
    op.drop_index(op.f('ix_other_documents_original_filename'), table_name='other_documents')
    op.drop_index(op.f('ix_other_documents_id'), table_name='other_documents')
    op.drop_table('other_documents')
    op.drop_index(op.f('ix_invoices_provider'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_original_filename'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
